"""
Notification Model

Represents a notification generated by the SmartPark system.

Notifications are business-event records that can be delivered through
multiple channels such as in-app notifications, SMS, email, or push.

The model intentionally separates:
- Notification type      -> what happened
- Notification channel   -> how it is delivered
- Notification status    -> delivery state
- Read state              -> whether the user has read it

This allows the notification subsystem to evolve independently from
the business modules that generate notification events.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

import sqlalchemy as sa
from sqlalchemy import (
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base_model import BaseModel
from app.models.enums import (
    NotificationChannel,
    NotificationPriority,
    NotificationStatus,
    NotificationType,
)

if TYPE_CHECKING:
    from app.models.user import User


class Notification(BaseModel):
    """
    System notification delivered to a user.

    A notification represents a single notification event on a
    specific delivery channel.

    Example:

        PAYMENT_SUCCESSFUL
        ├── IN_APP notification
        ├── SMS notification
        └── EMAIL notification

    Each channel is represented by its own Notification record.
    """

    __tablename__ = "notifications"

    __table_args__ = (
        # ======================================================
        # Query Performance
        # ======================================================

        Index(
            "ix_notifications_user_id",
            "user_id",
        ),

        Index(
            "ix_notifications_status",
            "status",
        ),

        Index(
            "ix_notifications_type",
            "type",
        ),

        Index(
            "ix_notifications_channel",
            "channel",
        ),

        Index(
            "ix_notifications_priority",
            "priority",
        ),

        Index(
            "ix_notifications_is_read",
            "is_read",
        ),

        Index(
            "ix_notifications_created_at",
            "created_at",
        ),

        Index(
            "ix_notifications_user_read",
            "user_id",
            "is_read",
        ),

        Index(
            "ix_notifications_related_entity",
            "related_entity_type",
            "related_entity_id",
        ),
    )

    # ==========================================================
    # Recipient
    # ==========================================================

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey(
            "users.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # ==========================================================
    # Classification
    # ==========================================================

    type: Mapped[NotificationType] = mapped_column(
        Enum(
            NotificationType,
            name="notification_type",
            create_type=False,
        ),
        nullable=False,
    )

    channel: Mapped[NotificationChannel] = mapped_column(
        Enum(
            NotificationChannel,
            name="notification_channel",
            create_type=False,
        ),
        nullable=False,
    )

    status: Mapped[NotificationStatus] = mapped_column(
        Enum(
            NotificationStatus,
            name="notification_status",
            create_type=False,
        ),
        nullable=False,
        default=NotificationStatus.PENDING,
        server_default=sa.text("'PENDING'"),
    )

    priority: Mapped[NotificationPriority] = mapped_column(
        Enum(
            NotificationPriority,
            name="notification_priority",
            create_type=False,
        ),
        nullable=False,
        default=NotificationPriority.NORMAL,
        server_default=sa.text("'NORMAL'"),
    )

    # ==========================================================
    # Content
    # ==========================================================

    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # ==========================================================
    # Read State
    # ==========================================================

    is_read: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
        server_default=sa.false(),
    )

    read_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=True,
    )

    # ==========================================================
    # Related Business Entity
    # ==========================================================

    related_entity_type: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
    )

    related_entity_id: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # ==========================================================
    # Delivery Provider Information
    # ==========================================================

    provider_message_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    failure_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ==========================================================
    # Relationships
    # ==========================================================

    user: Mapped["User"] = relationship(
        "User",
        foreign_keys=[user_id],
        lazy="select",
    )

    # ==========================================================
    # String Representation
    # ==========================================================

    def __repr__(self) -> str:
        return (
            f"<Notification("
            f"id={self.id}, "
            f"user_id={self.user_id}, "
            f"type='{self.type.value}', "
            f"channel='{self.channel.value}', "
            f"status='{self.status.value}')>"
        )