"""create parking facilities table

Revision ID: f200ea283f04
Revises: 2e2b24727ce2
Create Date: 2026-07-25 21:21:10.792933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f200ea283f04'
down_revision: Union[str, Sequence[str], None] = '2e2b24727ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_facilities',
    sa.Column('name', sa.String(length=150), nullable=False, comment='Display name of the parking facility.'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Unique business identifier for the parking facility.'),
    sa.Column('facility_type', sa.Enum('SHOPPING_MALL', 'UNIVERSITY', 'OFFICE', 'AIRPORT', 'HOSPITAL', 'HOTEL', 'RESIDENTIAL', 'PUBLIC', 'OTHER', name='facility_type', native_enum=False), nullable=False, comment='Business classification of the parking facility.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the parking facility.'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Country where the parking facility is located.'),
    sa.Column('county', sa.String(length=100), nullable=False, comment='County where the parking facility is located.'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City where the parking facility is located.'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Physical street address.'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal code.'),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False, comment='Latitude in decimal degrees.'),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False, comment='Longitude in decimal degrees.'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='IANA timezone.'),
    sa.Column('opening_time', sa.Time(), nullable=False, comment='Daily opening time.'),
    sa.Column('closing_time', sa.Time(), nullable=False, comment='Daily closing time.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates whether the facility is operational.'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_facility_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_facility_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_facilities_id'), 'parking_facilities', ['id'], unique=False)
    op.create_index('ix_parking_facility_code', 'parking_facilities', ['code'], unique=True)
    op.create_index('ix_parking_facility_name', 'parking_facilities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parking_facility_name', table_name='parking_facilities')
    op.drop_index('ix_parking_facility_code', table_name='parking_facilities')
    op.drop_index(op.f('ix_parking_facilities_id'), table_name='parking_facilities')
    op.drop_table('parking_facilities')
    # ### end Alembic commands ###
